DELETE FROM Pedido;
ALTER TABLE Pedido AUTO_INCREMENT = 1;

SET foreign_key_checks = 0;

DROP TEMPORARY TABLE IF EXISTS seed_numeros;
CREATE TEMPORARY TABLE seed_numeros AS
SELECT (@row := @row + 1) AS n
FROM
  (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
   UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t1,
  (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
   UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t2,
  (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
   UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t3,
  (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
   UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t4,
  (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
   UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t5,
  (SELECT 0 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
   UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) t6,
  (SELECT @row := 0) r
LIMIT 500000;


-- Insertamos todos los pedidos en una sola vez
INSERT INTO Pedido (numero, fecha, clienteNombre, total, estado, envio)
SELECT
    CONCAT('PED-', LPAD(n, 9, '0')) AS numero,
    DATE_ADD('2020-01-01', INTERVAL FLOOR(RAND() * 2190) DAY) AS fecha,
    CONCAT(
        ELT(FLOOR(1 + RAND()*10), 'Juan','María','Pedro','Laura','Andrés','Lucía','Sofía','Carlos','Julieta','Diego'),
        ' ',
        ELT(FLOOR(1 + RAND()*10), 'García','Pérez','Rodríguez','López','Fernández','Gómez','Torres','Romero','Díaz','Sánchez')
    ) AS clienteNombre,
    ROUND(1 + RAND() * 10000000, 2) AS total,
    ELT(FLOOR(1 + RAND()*3), 'NUEVO','FACTURADO','ENVIADO') AS estado,
    n AS envio
FROM seed_numeros
WHERE n BETWEEN 1 AND 500000;

SET foreign_key_checks = 1;




